# Generated by Django 2.2 on 2019-12-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_classics',
            field=models.BooleanField(default=False, verbose_name='是否经典'),
        ),
    ]
