# Generated by Django 2.2 on 2019-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursetag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': '课程标签', 'verbose_name_plural': '课程标签'},
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
