# Generated by Django 2.2 on 2019-12-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191206_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='notice',
            field=models.CharField(default='', max_length=300, verbose_name='课程公告'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courses', verbose_name='课程'),
        ),
    ]
