# Generated by Django 2.2 on 2019-12-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191206_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
