# Generated by Django 2.2 on 2019-12-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_courses_is_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.courses',),
        ),
    ]
