# Generated by Django 2.2 on 2019-12-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '用户消息', 'verbose_name_plural': '用户消息'},
        ),
    ]
